// <auto-generated />
using System;
using Education.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Education.Persistence.Migrations
{
    [DbContext(typeof(EducacionDbContext))]
    partial class EducacionDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Education.Domain.Curso", b =>
                {
                    b.Property<Guid>("CursoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaPublicacion")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Precio")
                        .HasPrecision(14, 2)
                        .HasColumnType("decimal(14,2)");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("CursoId");

                    b.ToTable("Cursos");

                    b.HasData(
                        new
                        {
                            CursoId = new Guid("3b49c270-9835-463d-b94d-ba6fc4c71ff7"),
                            Descripcion = "Curso de C# Basico",
                            FechaCreacion = new DateTime(2023, 12, 1, 22, 6, 9, 32, DateTimeKind.Local).AddTicks(5093),
                            FechaPublicacion = new DateTime(2025, 12, 1, 22, 6, 9, 32, DateTimeKind.Local).AddTicks(5107),
                            Precio = 56m,
                            Titulo = "C# desde cero hasta avanzado"
                        },
                        new
                        {
                            CursoId = new Guid("b28110a1-6d00-441e-bd72-bb52696ff08e"),
                            Descripcion = "Curso de Java",
                            FechaCreacion = new DateTime(2023, 12, 1, 22, 6, 9, 32, DateTimeKind.Local).AddTicks(5192),
                            FechaPublicacion = new DateTime(2025, 12, 1, 22, 6, 9, 32, DateTimeKind.Local).AddTicks(5193),
                            Precio = 25m,
                            Titulo = "Master en Java Spring desde las raices"
                        },
                        new
                        {
                            CursoId = new Guid("0d26ba72-1972-4d42-99a9-ce4afd96ba99"),
                            Descripcion = "Curso de Unit Test para NET Core",
                            FechaCreacion = new DateTime(2023, 12, 1, 22, 6, 9, 32, DateTimeKind.Local).AddTicks(5206),
                            FechaPublicacion = new DateTime(2025, 12, 1, 22, 6, 9, 32, DateTimeKind.Local).AddTicks(5207),
                            Precio = 100m,
                            Titulo = "Master en UNIT Test con CQRS "
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
